config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'

  get '/tasks/new', to:'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: :task

  post '/tasks', to: 'tasks#create'

  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'task#update'

  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control ' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control ' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>

  <div>
        <input type="checkbox" />
        <label for="completed">Completed</label>
    </div>
<% end %>

<div>
  <%= link_to "Back to list", task_path %>

</div>

app/views/tasks/index.html.erb
<div class="all_tasks">

  <h1>My tasks</h1>

  <ul>
    <% @tasks.each do |task|%>
        <li>
          <input type ="checkbox"><%= link_to task.title, task_path(task) %> <i class="fas fa-trash-alt"></i>
        </li>
    <% end %>
  </ul>

<hr>
  <div>
    <i class="fas fa-plus"></i><%= link_to "Add a new task", tasks_new_path %>
  </div>

</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control ' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control ' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<div>
  <%= link_to "Back to list", tasks_path %>

</div>

app/views/tasks/show.html.erb
<div class="show_task">

  <h1><%= @task.title %></h1>

  <p class='task_detail'><%= @task.details %></p>
  <button type="button" class="btn btn-info edit-btn"><%= link_to "Edit my task", edit_path %></button>

<hr>
  <p><%= link_to "Back to list", tasks_path %></p>

</div>